format = """
$username\
$directory\
$git_branch\
$docker_context
[î‚¶îƒŒ ](fg:Green)\
"""

# symbols: https://www.nerdfonts.com/cheat-sheet

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:Purple fg:White"
style_root = "bg:Purple fg:White"
format = """\
[ î‚¶](Purple)\
[ Zâ˜»llinger ]($style)\
[î‚´ ](fg:Purple)\
"""

[directory]
style = "bg:Blue fg:White"
format = """\
[î‚¶](fg:cyan)\
[ ](bg:cyan)\
[î‚¸](fg:cyan bg:blue)\
[$path]($style)\
[î‚¾](fg:cyan bg:blue)\
[ ](bg:cyan)\
[îƒŒ](fg:cyan)\
"""
truncation_length = 3 
truncation_symbol = "â™ª~ á••(á›)á•—/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh
[directory.substitutions]
style = "bg:Blue fg:White"
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "à² âŒ£à²  "
"git.trivir.com" = "ğ™ "
"github.houston.softwaregrp.net" = "â©„ "

# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "


[docker_context]
style = "bg:Blue fg:White"
symbol = "ïŒˆ "
format = "[ $symbol ]($style)"

[git_branch]
style = "bg:Green fg:white"
symbol = "î‚ "
format = """
[ îƒ”](fg:Green)\
[ on $symbol $branch ](fg:white bg:Green)\
[îƒ’ ](fg:Green)\
"""

